### ISSUE TITLE
Could not resolve "./components/FocusPoint"

### ISSUE THREAD

**Issue by jasperf** [EvodiaAut/vue-focuspoint-component#9]
Using this package in a Laravel Vue app. Updating from Laravel Mix now to Viet with our Vue 2.  Now stuck at `Could not resolve "./components/FocusPoint"`:

```
npm run dev

> dev
> vite


  VITE v3.2.6  ready in 716 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose

  LARAVEL v9.52.7  plugin v0.6.1

  ➜  APP_URL: https://site.test
✘ [ERROR] Could not resolve "./components/FocusPoint"

    node_modules/vue-focuspoint-component/src/index.js:1:23:
      1 │ import FocusPoint from './components/FocusPoint'
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~

/Users/user/code/site.com/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/vue-focuspoint-component/src/index.js:1:23: ERROR: Could not resolve "./components/FocusPoint"
    at failureErrorWithLog (/Users/user/code/site.com/node_modules/esbuild/lib/main.js:1575:15)
    at /Users/user/code/site.com/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/Users/user/code/site.com/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/Users/user/code/site.com/node_modules/esbuild/lib/main.js:1031:7)
    at /Users/user/code/site.com/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/Users/user/code/site.com/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/Users/user/code/site.com/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/Users/user/code/site.com/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 23,
        file: 'node_modules/vue-focuspoint-component/src/index.js',
        length: 25,
        line: 1,
        lineText: "import FocusPoint from './components/FocusPoint'",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Could not resolve "./components/FocusPoint"'
    }
  ],
  warnings: []
}
```

We use it in the Laravel Mediamanager loading it using

```
// resources/assets/vendor/MediaManager/js/components/utils/upload-preview.vue
...
<script>
import cloneDeep from 'lodash/cloneDeep'
import FocusPoint from 'vue-focuspoint-component'

export default {
    components: {
        FocusPoint
    },
    props: [
        'file',
        'fileTypeIs',
        'trans'
    ],
...
```

so we do use `import` ES2015 already. We also installed it of course:

```
npm list vue-focuspoint-component
site.com@ /Users/user/code/site.com
└── vue-focuspoint-component@2.0.1
```Any ideas what we might be missing here?

**Comment by jasperf** [comment]
It seems we need `import FocusPoint from './components/FocusPoint.vue'` in  `node_modules/vue-focuspoint-component/src/index.js` with `.vue` extension.

**Comment by EvodiaAut** [comment]
did it work now?

**Comment by jasperf** [comment]
@EvodiaAut Yeah, will close this thread now
